### PR TITLE
add show and output to Helper initialization

### PR DESCRIPTION
**Pull request by sierra-moxon**

### CODE REVIEW

**Comment by abessiari** [comment]
@sierra-moxon 

Seth tells me that this PR is not needed. He is giving me access to settings so that I can make sure the cicd workflow passes ... Please advise.

**Comment by abessiari** [comment]
> @abessiari Which settings do you need where?

The settings to this repository secrets ...

**Comment by sierra-moxon** [comment]
I belive this PR just forces the workflow to fail if any part of run.sh fails -- instead of pushing the docker container regardless of the run.sh targets fail.

**Comment by kltm** [comment]
Noting that the credentials part should be fixed now.
@sierra-moxon Is this closable or should it still be merged?

**Comment by sierra-moxon** [comment]
this PR just forces the workflow to fail if any part of run.sh fails.  I would merge it in.

**Comment by kltm** [comment]
@abessiari, if this looks good to you, please go ahead and merge.

**Pull request merged**
